/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import negocio.Administrador;
import negocio.Funcionario;

/**
 *
 * @author Renzo
 */
public class Funcionario_Main extends javax.swing.JFrame {

    private Funcionario funcionario;
    private Administrador administrador;

    /**
     * Creates new form Funcionario
     */
    public Funcionario_Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     *
     * @param funcionario
     */
    public Funcionario_Main(Funcionario funcionario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.funcionario = funcionario;
        this.label_titulo.setText("Bienvenido: " + this.funcionario.getNombre());
        this.setTitle("Principal Funcionario [" + this.funcionario.getRut() + "]");
        this.setSize(400, 400);
        this.jpanel_Admin.setVisible(false);
        this.jpanel_Admin.setEnabled(false);
        this.setResizable(false);
    }

    /**
     *
     * @param administrador
     */
    public Funcionario_Main(Administrador administrador) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.administrador = administrador;
        this.label_titulo.setText("Bienvenido: " + this.administrador.getNombre());
        this.setTitle("Principal Administrador  [" + this.administrador.getRut() + "]");
        this.setResizable(false);
        this.funcionario = new Funcionario();
        this.funcionario.setId(this.administrador.getId());
        this.funcionario.setSede(this.administrador.getSede());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fun_btn_realizarprestamo = new javax.swing.JButton();
        fun_btn_vigentes = new javax.swing.JButton();
        fun_btn_renopendientes = new javax.swing.JButton();
        jpanel_Admin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_man_usuarios = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_titulo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label_titulo.setText("Bienvenido:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menú", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 11))); // NOI18N

        fun_btn_realizarprestamo.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        fun_btn_realizarprestamo.setText("Realizar Préstamo");
        fun_btn_realizarprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fun_btn_realizarprestamoActionPerformed(evt);
            }
        });

        fun_btn_vigentes.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        fun_btn_vigentes.setText("<html><center>Préstamos Vigentes (Renovaciones y Devoluciones)</center></html>");
        fun_btn_vigentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fun_btn_vigentesActionPerformed(evt);
            }
        });

        fun_btn_renopendientes.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        fun_btn_renopendientes.setText("Renovaciones Pendientes");
        fun_btn_renopendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fun_btn_renopendientesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setText("Mantenedores");

        jButton1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jButton1.setText("Textos");

        jButton2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jButton2.setText("Autores");

        btn_man_usuarios.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btn_man_usuarios.setText("Usuarios");
        btn_man_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_man_usuariosActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jButton4.setText("Bibliotecas");

        javax.swing.GroupLayout jpanel_AdminLayout = new javax.swing.GroupLayout(jpanel_Admin);
        jpanel_Admin.setLayout(jpanel_AdminLayout);
        jpanel_AdminLayout.setHorizontalGroup(
            jpanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jpanel_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_man_usuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpanel_AdminLayout.setVerticalGroup(
            jpanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_man_usuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fun_btn_realizarprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fun_btn_vigentes, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fun_btn_renopendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(385, Short.MAX_VALUE))
            .addComponent(jpanel_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fun_btn_realizarprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fun_btn_vigentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fun_btn_renopendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jpanel_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_titulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fun_btn_vigentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fun_btn_vigentesActionPerformed
        Funcionario_RevisarPrestamos funPrestamos = new Funcionario_RevisarPrestamos(this.funcionario);
        funPrestamos.setVisible(true);
    }//GEN-LAST:event_fun_btn_vigentesActionPerformed

    private void fun_btn_renopendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fun_btn_renopendientesActionPerformed
        Funcionario_RenovacionesPendientes funPrestamos = new Funcionario_RenovacionesPendientes(this.funcionario);
        funPrestamos.setVisible(true);
    }//GEN-LAST:event_fun_btn_renopendientesActionPerformed

    private void fun_btn_realizarprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fun_btn_realizarprestamoActionPerformed
        Funcionario_NuevoPrestamo funPrestamos = new Funcionario_NuevoPrestamo(this.funcionario);
        funPrestamos.setVisible(true);
    }//GEN-LAST:event_fun_btn_realizarprestamoActionPerformed

    private void btn_man_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_man_usuariosActionPerformed
        Administrador_Manten_Usuarios man_usuarios = new Administrador_Manten_Usuarios(this.administrador);
        man_usuarios.setVisible(true);
    }//GEN-LAST:event_btn_man_usuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionario_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionario_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionario_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionario_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionario_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_man_usuarios;
    private javax.swing.JButton fun_btn_realizarprestamo;
    private javax.swing.JButton fun_btn_renopendientes;
    private javax.swing.JButton fun_btn_vigentes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpanel_Admin;
    private javax.swing.JLabel label_titulo;
    // End of variables declaration//GEN-END:variables
}
