/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.Funcionario;
import negocio.Libro;
import negocio.Prestamo;
import negocio.Usuario;

/**
 *
 * @author Renzo
 */
public class Funcionario_NuevoPrestamo extends javax.swing.JFrame {

    Funcionario funcionario;
    Libro libroaPrestar;
    Usuario usuarioaPrestar;
    Prestamo prestamoNuevo;

    /**
     * Creates new form Funcionario_Prestamo
     */
    public Funcionario_NuevoPrestamo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     *
     * @param funcionario
     */
    public Funcionario_NuevoPrestamo(Funcionario funcionario) {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            this.funcionario = funcionario;
            this.usuarioaPrestar = new Usuario();
            this.prestamoNuevo = new Prestamo();
        } catch (Exception ex) {
            Logger.getLogger(Funcionario_NuevoPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fprestamo_label_advertencia = new javax.swing.JLabel();
        fprestamo_filtro_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fprestamo_submit = new javax.swing.JButton();
        txt_rut_usuario = new javax.swing.JTextField();
        btn_validarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_textos_prestamo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Registro de préstamos");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel2.setText("Prestar a (RUT):");

        fprestamo_label_advertencia.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        fprestamo_label_advertencia.setText("Advertencia !:");

        fprestamo_filtro_nombre.setColumns(10);
        fprestamo_filtro_nombre.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        fprestamo_filtro_nombre.setEnabled(false);
        fprestamo_filtro_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fprestamo_filtro_nombreKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel3.setText("Filtro de Nombre");

        fprestamo_submit.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        fprestamo_submit.setText("Realizar Préstamo");
        fprestamo_submit.setEnabled(false);
        fprestamo_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fprestamo_submitActionPerformed(evt);
            }
        });

        btn_validarUsuario.setText("Validar Usuario");
        btn_validarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validarUsuarioActionPerformed(evt);
            }
        });

        tbl_textos_prestamo.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        tbl_textos_prestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Autor", "Genero", "Idioma", "Cantidad", "Páginas", "Demanda", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_textos_prestamo.setEnabled(false);
        tbl_textos_prestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_textos_prestamoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_textos_prestamo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fprestamo_submit)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fprestamo_filtro_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fprestamo_label_advertencia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_rut_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_validarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_rut_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_validarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fprestamo_filtro_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fprestamo_label_advertencia)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fprestamo_submit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_validarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validarUsuarioActionPerformed
        try {
            String usuarioRut = this.txt_rut_usuario.getText();
            if (ValidacionRut.IngresoRut(usuarioRut)) {
                this.usuarioaPrestar = new Usuario(usuarioRut);
                this.libroaPrestar = new Libro();
                if (this.usuarioaPrestar.obtenerDatosPrestamo()) {
                    this.fprestamo_filtro_nombre.setEnabled(true);
                    this.fprestamo_submit.setEnabled(true);
                    this.tbl_textos_prestamo.setEnabled(true);
                    this.listarlibros();
                } else {
                    JOptionPane.showMessageDialog(null, "Rut no existe en Biblioteca!", "Rut mal ingresado!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Rut ingresado no es valido!", "Rut mal ingresado!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_validarUsuarioActionPerformed

    private void fprestamo_filtro_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fprestamo_filtro_nombreKeyReleased
        try {
            String nombreLibro = this.fprestamo_filtro_nombre.getText();
            this.filtrarlibros(nombreLibro);
        } catch (SQLException ex) {
            Logger.getLogger(Funcionario_NuevoPrestamo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error inesperado!\nFavor contactar al administrador del sistema.", "Error!", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(Funcionario_NuevoPrestamo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error inesperado!\nFavor contactar al administrador del sistema.", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_fprestamo_filtro_nombreKeyReleased

    private void tbl_textos_prestamoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_textos_prestamoMouseReleased
        int selectedRow = this.tbl_textos_prestamo.getSelectedRow();
        if (selectedRow > -1) {
            String demandaLibro = (String) this.tbl_textos_prestamo.getValueAt(selectedRow, 7);
            int idLibro = (Integer) this.tbl_textos_prestamo.getValueAt(selectedRow, 0);
            this.libroaPrestar.setId(idLibro);
            String advertencia;
            switch (demandaLibro) {
                case "Alta":
                    advertencia = (this.usuarioaPrestar.getPerfil() == 3) ? "3 dias." : "2 dias.";
                    this.fprestamo_label_advertencia.setText("Advertencia: El texto solicitado es de demanda Alta. La duración del prestamo será de " + advertencia);
                    this.fprestamo_label_advertencia.setForeground(Color.RED);
                    this.libroaPrestar.setDemanda("Alta");
                    break;
                case "Normal":
                    advertencia = (this.usuarioaPrestar.getPerfil() == 3) ? "10 dias." : "5 dias.";
                    this.fprestamo_label_advertencia.setText("Advertencia: El texto solicitado es de demanda Alta. La duración del prestamo será de " + advertencia);
                    this.fprestamo_label_advertencia.setForeground(Color.BLACK);
                    this.libroaPrestar.setDemanda("Normal");
                    break;
            }
        }
    }//GEN-LAST:event_tbl_textos_prestamoMouseReleased

    private void fprestamo_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fprestamo_submitActionPerformed
        try {
            this.prestamoNuevo.setPrestamo_usuario(this.usuarioaPrestar.getId());
            this.prestamoNuevo.setPerfil_usuario(this.usuarioaPrestar.getPerfil());
            this.prestamoNuevo.setPrestamo_libro(this.libroaPrestar.getId());
            this.prestamoNuevo.setPrestamo_sede(this.funcionario.getSede());
            this.prestamoNuevo.setDemanda_libro(this.libroaPrestar.getDemanda());
            this.prestamoNuevo.setPrestamo_funcionario(this.funcionario.getId());
            this.prestamoNuevo.registrarPrestamo();
        } catch (Exception ex) {
            Logger.getLogger(Funcionario_NuevoPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fprestamo_submitActionPerformed

    private void listarlibros() throws SQLException {
        Libro libro = new Libro();
        ResultSet rs = libro.getTodoLibrosTabla();
        this.llenarTabla(rs);
    }

    private void filtrarlibros(String filtro_nombre) throws SQLException, Exception {
        Libro libro = new Libro();
        ResultSet rs = libro.filtrarLibreria(filtro_nombre);
        this.llenarTabla(rs);
    }

    private void llenarTabla(ResultSet rs) throws SQLException {
        while (tbl_textos_prestamo.getRowCount() > 0) {
            ((DefaultTableModel) tbl_textos_prestamo.getModel()).removeRow(0);
        }
        int columns = rs.getMetaData().getColumnCount();
        while (rs.next()) {
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++) {
                row[i - 1] = rs.getObject(i);
            }
            ((DefaultTableModel) tbl_textos_prestamo.getModel()).insertRow(rs.getRow() - 1, row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionario_NuevoPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionario_NuevoPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionario_NuevoPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionario_NuevoPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionario_NuevoPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_validarUsuario;
    private javax.swing.JTextField fprestamo_filtro_nombre;
    private javax.swing.JLabel fprestamo_label_advertencia;
    private javax.swing.JButton fprestamo_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_textos_prestamo;
    private javax.swing.JTextField txt_rut_usuario;
    // End of variables declaration//GEN-END:variables
}
